### ISSUE TITLE
Rework header styling

### ISSUE THREAD

**Issue by ArnoldVanN** [ArnoldVanN/james-webb-news#4]
The header is pretty ugly. Needs to be reworked. Maybe a slanted edge on the bottom of the header image, fading and/or shade on the top and bottom of the image and change the color of the navbar to white. Also maybe make the header image static so it looks better when you scroll past.

**Comment by ekkaaditya200** [comment]
Hey i want to work on this can i get it assigned

**Comment by ArnoldVanN** [comment]
@ekkaaditya200 Hey bro, honestly this project was meant for me and possibly some friends to learn React but you're free to fork the repo if you wanna try to work on it. You can make a PR whenever you're finished with this task and if I like it i'll merge it and add you as a collaborator :)
